# Generated by Django 5.2.4 on 2025-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Главное изображение'),
        ),
    ]
