# Generated by Django 5.2.4 on 2025-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_muralsuggestion_news_mural_latitude_mural_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('before_image', models.ImageField(upload_to='gallery/before/')),
                ('after_image', models.ImageField(upload_to='gallery/after/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
