# Generated by Django 5.2.6 on 2025-09-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_muralsuggestion_news_mural_latitude_mural_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('category', models.CharField(choices=[('college', 'Мероприятия в колледже'), ('dorm', 'Мероприятия в общежитии'), ('cultural', 'Культурные мероприятия')], default='college', max_length=20, verbose_name='Категория')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название исторического места/события')),
                ('description', models.TextField(verbose_name='Описание места/события')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('before_image', models.ImageField(upload_to='gallery/before/')),
                ('after_image', models.ImageField(upload_to='gallery/after/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college_images/', verbose_name='Изображение')),
                ('college_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.college')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history_images/', verbose_name='Изображение')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.history')),
            ],
        ),
    ]
