# Generated by Django 5.2.6 on 2025-10-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_college_history_improvementgallery_collegeimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='video_url',
        ),
        migrations.AddField(
            model_name='mural',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='murals/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='mural',
            name='image',
            field=models.ImageField(upload_to='murals/images/', verbose_name='Главное изображение'),
        ),
    ]
